Repository ministryofjustice/laa-manage-your-civil-cases, pull requests merged in 2025-09, with the labels that each got.

#246 Chore/el 2592 actions checkout upgrade
  .github/workflows/publish-documentation.yml
  docs/makefile
Labels: Approved

#249 fixing to use correct deploy method
  .github/workflows/publish-documentation.yml
Labels: Approved

#252 EL-2460: Add third party details
  locales/en.json
  routes/editClientDetails.ts
  src/middlewares/clientEmailAddressSchema.ts
  src/middlewares/clientThirdPartySchema.ts
  src/middlewares/index.ts
  src/scripts/controllers/addClientThirdPartyController.ts
  src/scripts/controllers/index.ts
  src/scripts/helpers/formControllerHelpers.ts
  src/scripts/helpers/index.ts
  src/services/apiService.ts
  tests/unit/controllers/addClientThirdPartyController.spec.ts
  views/case_details/_client-details-partial.njk
  views/case_details/third_party_details/_form.njk
  views/case_details/third_party_details/add-client-third-party.njk
Labels: Ready For Review

#270 EL-2560: 'Client support needs' summary card & CTA button
  locales/en.json
  src/services/apiService.ts
  types/case-types.ts
  views/case_details/_client-details-partial.njk
  views/components/summaryCardComponent.njk
Labels: Approved, UAT

#276 EL-2565: Remove client support needs interstitial page & functionality
  locales/en.json
  routes/caseDetails.ts
  src/scripts/controllers/index.ts
  src/scripts/controllers/removeClientSupportNeeds.ts
  src/services/apiService.ts
  tests/unit/controllers/removeClientSupportNeeds.spec.ts
  views/case_details/confirm-remove-client-support-needs.njk
  views/components/confirmationComponent.njk
Labels: Approved, UAT

#282 EL-2658 Updates libraries identified in dependabot
  package.json
  tests/unit/utils/displayAsciiBanner.spec.ts
  utils/displayAsciiBanner.ts
  yarn.lock
Labels: Approved, UAT

#264 EL-2650 Refactor Search Controller to use existing session storage helpers
  src/scripts/controllers/searchController.ts
  tests/unit/controllers/searchController.spec.ts
Labels: Approved, UAT

#287 EL-2665: Update to "eslint-plugin-jsdoc": "^60.3.0"
  package.json
  yarn.lock
Labels: Approved

#277 EL-2561: Add client support needs page
  locales/en.json
  package.json
  routes/editClientDetails.ts
  src/middlewares/clientSupportNeedsSchema.ts
  src/middlewares/index.ts
  src/scripts/controllers/addClientSupportNeedsController.ts
  src/scripts/controllers/index.ts
  src/scripts/frontendPackagesEntry.ts
  src/scripts/helpers/ValidationDateHelpers.ts
  src/scripts/helpers/dataTransformers.ts
  src/scripts/helpers/formControllerHelpers.ts
  src/scripts/helpers/index.ts
  src/scss/main.scss
  src/services/apiService.ts
  tests/unit/controllers/addClientSupportNeedsController.spec.ts
  types/form-controller-types.ts
  types/frontend-packages-types.d.ts
  utils/nunjucksSetup.ts
  views/case_details/client_support_needs/_base-client-support-needs.njk
  views/case_details/client_support_needs/_form.njk
  views/case_details/client_support_needs/add-client-support-needs.njk
  views/case_details/client_support_needs/change-client-support-needs.njk
  views/case_details/client_support_needs/languages.json
  views/case_details/third_party_details/add-client-third-party.njk
  views/case_details/third_party_details/change-client-third-party.njk
  yarn.lock
Labels: Approved, UAT

#289 EL-2670: Accessible autocomplete clears selection, when input is empty
  views/case_details/client_support_needs/_base-client-support-needs.njk
Labels: Approved, UAT
