Repository ministryofjustice/laa-manage-your-civil-cases, pull requests merged in 2025-07, with the labels that each got.

#133 EL-2481: Change username to plain text
  views/base.njk
Labels: Approved, UAT

#125 EL-2463 Disables client side sorting
  src/scss/components/_sortable-table.scss
  src/scss/main.scss
  tests/e2e/helpers/sorting-helpers.ts
  tests/e2e/home-page.spec.ts
  tests/e2e/new_cases.spec.ts
  tests/e2e/shared/global-shared-test.ts
  tests/e2e/shared/table-sorting-shared-test.ts
  tests/e2e/your-cases-page.spec.ts
  views/cases/_accepted-partial.njk
  views/cases/_closed-partial.njk
  views/cases/_new-partial.njk
  views/cases/_opened-partial.njk
  views/cases/index.njk
  views/components/paginationComponent.njk
  views/components/sortableTableComponent.njk
Labels: Approved, UAT

#136 EL-2472: Bump node version to 24.3.0
  .github/workflows/deploy.yml
  .github/workflows/mocha.yml
  .github/workflows/playwright.yml
  .nvmrc
  Dockerfile
  README.md
  package.json
Labels: Ready For Review

#137 EL-2474/EL-2475: Updates "@typescript-eslint/parser" to 8.35.0 & "eslint-plugin-jsdoc" to 51.3.1
  eslint.config.js
  package.json
  yarn.lock
Labels: Ready For Review

#145 EL-2498 Updates libraries mentioned in dependabots
  package.json
  yarn.lock
Labels: Approved, UAT

#132 EL-2381: Sub navigation for client details page
  routes/yourCases.ts
  views/cases/client-details.njk
Labels: Approved, UAT

#144 EL-2497 Further fixes to sortOrder and Dummy Data
  playwright.config.ts
  routes/yourCases.ts
  tests/e2e/shared/table-sorting-shared-test.ts
  tests/e2e/your-cases-page.spec.ts
  tests/fixtures/cases/accepted/data-asc.json
  tests/fixtures/cases/accepted/data-desc.json
  tests/fixtures/cases/all-client-details.json
  tests/fixtures/cases/new/data-asc.json
  tests/fixtures/cases/new/data-desc.json
  views/cases/_accepted-partial.njk
  views/cases/_closed-partial.njk
  views/cases/_new-partial.njk
  views/cases/_opened-partial.njk
Labels: Approved, UAT

#146 EL-2492: Updates "@types/node" to 24.0.12
  package.json
  yarn.lock
Labels: Approved

#152 EL-2438: Group MCC Dependabot updates
  .github/dependabot.yml
Labels: Ready For Review

#166 EL-2512: Dependabot updates
  .github/workflows/deploy.yml
  .github/workflows/mocha.yml
  .github/workflows/playwright.yml
  .nvmrc
  Dockerfile
  README.md
  eslint.config.js
  package.json
  yarn.lock
Labels: Approved

#164 EL-2502: Migrate GitHub Actions Environment Variables to Helm Values
  .github/actions/deploy/action.yml
  .github/workflows/deploy.yml
  deploy/laa-manage-your-civil-cases/values/production.yaml
  deploy/laa-manage-your-civil-cases/values/staging.yaml
  deploy/laa-manage-your-civil-cases/values/uat.yaml
  scripts/deploy.sh
Labels: Approved

#148 EL-2499 Use MockAPI rather than local JSON
  .c8rc.json
  .env.example
  .github/actions/deploy/action.yml
  .github/workflows/deploy.yml
  .github/workflows/mocha.yml
  .github/workflows/playwright.yml
  config.ts
  deploy/laa-manage-your-civil-cases/templates/deployment.yaml
  deploy/laa-manage-your-civil-cases/values/production.yaml
  deploy/laa-manage-your-civil-cases/values/staging.yaml
  deploy/laa-manage-your-civil-cases/values/uat.yaml
  routes/caseDetails.ts
  routes/index.ts
  routes/yourCases.ts
  scripts/deploy.sh
  src/scripts/helpers/README.md
  src/scripts/helpers/dataTransformers.ts
  src/scripts/helpers/errorHandler.ts
  src/scripts/helpers/index.ts
  src/services/apiService.ts
  src/services/authService.ts
  tests/e2e/fixtures/mock-data.json
  tests/e2e/helpers/sorting-helpers.ts
  tests/e2e/shared/global-shared-test.ts
  tests/e2e/shared/table-sorting-shared-test.ts
  tests/e2e/your-cases-page.spec.ts
  tests/fixtures/cases/accepted/data-asc.json
  tests/fixtures/cases/accepted/data-desc.json
  tests/fixtures/cases/all-client-details.json
  tests/fixtures/cases/closed/data-asc.json
  tests/fixtures/cases/closed/data-desc.json
  tests/fixtures/cases/new/data-asc.json
  tests/fixtures/cases/new/data-desc.json
  tests/fixtures/cases/opened/data-asc.json
  tests/fixtures/cases/opened/data-desc.json
  types/api-types.ts
  types/auth-types.ts
  types/case-types.ts
  types/config-types.ts
  utils/axiosSetup.ts
  views/case_details/_client-details-partial.njk
  views/components/sortableTableComponent.njk
Labels: Approved, UAT

#162 EL-2442: Create third party details summary card
  views/case_details/_client-details-partial.njk
Labels: Approved, UAT

#177 EL-2419: Edit Client name
  routes/caseDetails.ts
  routes/editClientDetails.ts
  routes/index.ts
  routes/yourCases.ts
  src/scripts/controllers/caseDetailsController.ts
  src/scripts/controllers/editClientDetailsController.ts
  src/scripts/controllers/yourCasesController.ts
  src/scripts/custom.ts
  src/scripts/helpers/formValidationRules.ts
  src/scripts/helpers/index.ts
  src/scripts/helpers/validateForm.ts
  src/scripts/pages/yourCases.ts
  src/services/apiService.ts
  types/form-validation.ts
  views/case_details/_client-details-partial.njk
  views/case_details/edit-client-name.njk
  views/components/errorSummaryComponent.njk
Labels: Approved, UAT

#182 EL-2454: Change client email address
  routes/editClientDetails.ts
  src/scripts/controllers/editClientDetailsController.ts
  src/scripts/helpers/formValidationRules.ts
  tests/e2e/client_detials_edit_email_address.spec.ts
  types/form-validation.ts
  views/case_details/_client-details-partial.njk
  views/case_details/edit-client-email-address.njk
Labels: Approved, UAT

#185 EL-2555: Bump actions/checkout from 3 to 4
  .c8rc.json
  .github/workflows/dependency-review.yml
  .github/workflows/deploy.yml
Labels: Approved

#187 EL-2562: Chore: add tests to improve code coverage
  .github/workflows/mocha.yml
  eslint.config.js
  playwright.config.ts
  src/scripts/controllers/editClientDetailsController.ts
  tests/unit/controllers/caseDetailsController.spec.ts
  tests/unit/controllers/editClientDetailsController.spec.ts
  tests/unit/controllers/yourCasesController.spec.ts
  tests/unit/helpers/formValidationRules.spec.ts
  tests/unit/helpers/validateForm.spec.ts
  tsconfig.json
  types/csrf-types.ts
Labels: Approved
