Repository ministryofjustice/laa-manage-your-civil-cases, pull requests merged in 2025-05, with the labels that each got.

#37 EL-2276: Finish off Github actions job for pushing tech docs, Part 2
  .github/workflows/publish-documentation.yml
Labels: Approved

#40 BUG: EL-2276: Finish off Github actions job for pushing tech docs, Part 3
  .github/workflows/publish-documentation.yml
Labels: Ready For Review, Approved

#38 BUG: EL-2245: remove `.husky/pre-commit` file and go with version when initialised
  .husky/pre-commit
Labels: Approved

#36 Improve deploy Github action
  .github/workflows/deploy.yml
  scripts/deploy.sh
Labels: Approved

#47 EL-2287: Jira integration for MCC
  .github/workflows/gajira.yml
Labels: Ready For Review

#71 EL-2283: Add github action to delete UAT releases after merge
  .github/actions/delete-uat-release/action.yml
  .github/workflows/delete_uat_release.yml
Labels: Approved
